version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    working_directory: ~/repo

    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common

      - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - run: sudo apt-key fingerprint 0EBFCD88
      - run: |
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

      - run: sudo apt-get update
      - checkout
      - run: ./gradlew test --stacktrace
      - store_test_results:
          path: build/reports/tests/test